### ISSUE TITLE
Amazing

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [DarkWav/SAC#34]
This is best plugin ever!
It works so good!

You should add a donation button, for your time loss in coding it!

**Comment by DarkWav** [comment]
Thanks so much! Since im not and adult developer (im under 18) it is not possible for me to take anything.
Its enough for me to see people being happy (i really enjoy that). I personally really hate hackers and its fun to make them rage by writing an AntiCheat :) .
If you want, you can also leave a review at [ImagicalMine Forums](https://imgcl.co/plugins/sac-shadowanticheat.52/)

**Comment by TDMidkwhatisxd** [comment]
Im didnt close? I had hard time to find it!

**Comment by DarkWav** [comment]
should i close the issue?

**Comment by TDMidkwhatisxd** [comment]
Ya, and block comments!
Btw! Is there a way to detect server loads? To improve your anticheat, you should double the detection time wen server have high loads, to avoid ppl get kicked for nothing!
Elytra will get detected by speed hack!

Just leting you know!
And your should have a nuker detection! Multiple block breaks should be canceled!

**Comment by DarkWav** [comment]
i already have nuker detection planned.
elytras are still an issue as they are only implemented thruogh a plugin.
i already have an anti-lag mechanism built-in in AntiSpeed and AntiInstantKill.
But i will work on that for other checks.
