### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by Infernus101** [DarkWav/SAC#5]
Please Fix the PlayerJoinEvent Lag as seen in the pic, this is by far the best anticheat plugin for MCPE servers BTW! VAC - FTW
![untitled](https://cloud.githubusercontent.com/assets/20124897/19016288/2434e6d6-8833-11e6-8b67-f80671bd364b.png)

**Comment by DarkWav** [comment]
make sure you are not under DDOS Attack because that could cause it.
Is this really lagging your server (visible lag in-game) ?
is this the same with no futher plugins installed?
Which server software are you using?

### in the OnJoin() event, the Observer is generated. <br> the Observer does ALL the AntiCheating.

Sorry, i code my plugin as fast as possible, but AntiCheating is very CPU/RAM expensive.
for every player that joins, yor server will need 20 KB of RAM more.
THat means:
100 Players more: 1 MB RAM more
100000 Players more (very unrealistic) : 1 GB RAM MORE!
Is the total PCT of 2% already lagging your server?
please report.

**Comment by Infernus101** [comment]
i dont know about visible lag because many plugins are there.
i cant see with no plugins installed because then no players will be online.
Genisys.
I have a max of only 80 players, and 4 gb ram, so why is it lagging?

**Comment by DarkWav** [comment]
is a PCT of 2% lagging? i think 2% is still ok. correct me if im wrong.

**Comment by Infernus101** [comment]
its much for me compared because i have other plugins too

**Comment by DarkWav** [comment]
and BTW this has nothing to do with PlayerJoin. your programm only tells the eventlistener.
but its the observer (whis ACTUALLY is the AntiCheat) that causer the Lag, but is shown as onJoin()
I am sorry, but, as i said, AntiCheating is timeexpenisve.
I have to check every single move, hit, regeneration for thounsands of things.
I am continiously trying to make this faster, but a massive general speed improvement is not possible so far. the phar plugin is 50 KB big and that means really big. 
as i said, all the checking is not that CPU/RAM-friendly.
I can only say: of couse an AntiCHeat plugin will take mor RAM/CPU usage than a Protect/Minigame/Fun Plugin. sorry.
However, im always trying to make this as fast as possible.

**Comment by Infernus101** [comment]
okay

**Comment by DarkWav** [comment]
How did you profile the sever (with wich profiler)

**Comment by Infernus101** [comment]
I think that tick world problem is causing more lag, because player complained about getting tp'd back to where they started and i think that world tick issue i opened is causing that!! Please fix

**Comment by DarkWav** [comment]
2% PCT CANT cause LAG. (expect of if you on a REALLY SLOW system.)
I can only say that VAC is as fast as possible.
and the tpback has nothing to do with lag because speed still works on laggy servers (i made it so it works with lag! (it depends on server TPS))
"tick world" is something that i never heard of.

### i can only help if i know the profiling ways...

**Comment by DarkWav** [comment]
closed with commit 90a5abc1f5412fbcae11fdf1c87882d3a07f1c48
