### ISSUE TITLE
Bugs at jumping on specific blocks

### ISSUE THREAD

**Issue by ghost** [DarkWav/SAC#53]
I use version 3.2.5 (latest)

See video here: https://youtu.be/hVgMtMdRDy0
Config: https://pastebin.com/zrTezXbH
I changed the anti killaura thingy becuase there were too much false positives. There are still fp's in the current settings btw
------------------------------------------------------------------------------------------------------

**Comment by ghost** [comment]
Would be happy if you could se3nd your discord tag or something else to further discuss some bugs i found

**Comment by DarkWav** [comment]
first of all, sorry for the insane delay of my response. I had a huge amount of holydays (14 days) (and had exams before).
This seems to be a critical error in antifly or noclip. i will try to reproduce the issue ASAP.

**Comment by DarkWav** [comment]
and your configuration seems corrupted to me:
1. setting the fly punishment to "none" completly disables the antifly check. it needs to be "Block" or "kick"
(unless you are using a standalone antifly plugin)
2. setting "KillAura" to "false" disables the entire combat protection. in would at least enable Angle
(You do not need to activate the heuristics at all if you wish.
Minimum protection level settings: 
#----------------KillAura-----------------#
#BETA, REPORT BUGS!
#Do you want to enable KillAura check?
#This also catches AimAura and KillAuraLegit.
#This will block anything that gives the player
#a sanificant gamplay advantage, not useless bots.
#TP-Aura is handled by Speed. This is purely behavoir
#based, it does not spawn any fake entities.
 
   KillAura: true
 
#Angle (3rd-person-pvp prevention)
#This will block hitting with impossible angles.
#(blocks hitting behind yourself)
#This is pretty basic and will not cause false
#positives or false alerts.
#Do you want to enable Angle?
 
   Angle: true
 
#Advanced KillAura Heuristics And Detection (AKAHAD)
#This is an advanced algorithm to catch a lot more
#combat hacks. This is generally aggersive, but
#you can make it even more agersive or rather
#permissive, but i recommend leaving it as it is.
#How strong should AKAHAD be configured?
#
# 0 = DISABLE AKAHAD
# 1 = PERMISSIVE
# 2 = NORMAL
# 3 = AGGRESSIVE
#
# PREMISSIVE will cause close to zero false positives
# even on large servers, but detection is slow and
# bypasses are more likely.
#
# NORMAL will catch most KillAuras, with a very little
# chanche of both false positives and negatives.
# I would recommand this setting because it is the most
# efficent and has the most usability.
#
# AGGRESSIVE will catch nearly every KillAura very fast,
# even triggerbots are detected. This configuration is
# very agressive and may cause false positives depending
# on the situation. If you set "KillAura-Threshold" to
# 45 it can be very effective. USE AT YOUR OWN RISK!
#
#I reccomand to use PERMISSIVE if you have a big server.
#For other servers, use NORMAL for a normal server , only
#use AGGRESSIVE if you have a smaller server or massive
#problems with KillAura hackers.
 
   AKAHAD: 0
 
#MacroCapture (Triggerbot/Macro detection)
#This is a component of AKAHAD you can configure.
#This will NOT work if AKAHAD is diabled!
#
# 0 = DISABLE MacroCapture
# 1 = PREMISSIVE
# 2 = AGGRESSIVE
#
# PREMISSIVE will catch some Macros and helps the KillAura
# Check to perform better.
# Works best with AKAHAD set to PREMISSIVE or NORMAL.
#
# AGGRESSIVE will catch nearly every combat hack in existance,
# but should be used with high thresholds.
# Works best with AKAHAD set to AGGRESSIVE.
#
#I would recommend to use AGGRESSIVE if you have many hackers,
#for any other case use PERMISSIVE.
 
   AKAHAD-MacroCapture: 0
 
#AimbotCatcher
#This is and old mechanisim to catch aimaura and aimbots in
#general. It is known for causing a lot of false alerts
#on windows 10 edition. it will work on MCPE but
#it is a risk to activate it. I would NOT recommend to
#enable this. USE AT YOUR OWN RISK!
 
   AimbotCatcher: false
 
#How many times must a player hack before detection?
#35 Should work fine. (Standard)
#NEVER set this lower than 25
#For PREMISSIVE AKAHAD: 25
#For   NORMAL   AKAHAD: 35
#For AGGRESSIVE AKAHAD: 45
#Increase if KillAura causes false poitives.
 
   KillAura-Threshold: 35
 
#Wich Message Sould be shown if KillAura is detected?
 
   KillAura-Message: "[SAC] > KillAura is not allowed!"
 
#Which Log Message Sould be shown if KillAura is detected?
 
   KillAura-LogMessage: "[SAC] > %PLAYER% is hacking KillAura!"

**Comment by ghost** [comment]
So as for the AntiFlying punishment, didnt know that i have set that to none lol.
And as i said, Killaura Detection is causing massive FalsePositives and legit players were getting kicked more often that actual hackers

**Comment by DarkWav** [comment]
KillAura has many, many modules and some of them CAN cause false alerts (e.g AKAHAD-MacroCapture,
AimCatcher) , some cant at all (eg. Angle) and some have a very little chance (eg. AKAHAD WITHOUT MacroCapture enabed and on normal - permissive mode) I would reccomend to eneble the killaura check
as a whole, and then disabling everything but "Angle". That should work even on huge servers.
If the bug still ocurrs then, it is an internal error of the killaura module, and that means i have to add
a config option for that. Currently there is still a part of code in killaura that can cause FPs and cant
be configured or turned off, I will add a config option in the next patch

**Comment by ghost** [comment]
Ok, thanks. I will definetely try it. Im hosting a TestServer and thats why i set everything to block(/none). I would like to see a better setback system. In case of flying, the hacker (or in a rare cse a legit) will be stuck in air :/. In my own anticheat i solved it by setting a "checkpoint" each time the player is on ground.

**Comment by DarkWav** [comment]
# All old issues will be closed today. 
**If this bug still occurs, please open a new issue. 
Im sorry for not being able to handle all old issues, but my time is very limited.**
