### ISSUE TITLE
Crash new version = BUG

### ISSUE THREAD

**Issue by Pet0nov** [DarkWav/SAC#71]
[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] [12:36:24] [Server thread/WARNING]: Timezone could not be automatically determined. An incorrect timezone will result in incorrect timestamps on console logs. It has been set to "UTC" by default. You can change it on the php.ini file.
[Server] [12:36:24] [Server thread/INFO]: Loading pocketmine.yml...
[Server] [12:36:24] [Server thread/INFO]: Loading bluelight.properties...
[Server] [12:36:24] [Server thread/INFO]: Loading server properties...
[Server] [12:36:24] [Server thread/INFO]: Selected English (eng) as the base language
[Server] [12:36:24] [Server thread/INFO]: Starting Minecraft: PE server version v1.0.8 alpha
[Server] [12:36:24] [Server thread/INFO]: Opening server on 0.0.0.0:19132
[Server] [12:36:24] [Server thread/INFO]: This server is running PocketMine-MP-DerivedVersion version 2.0dev "BlueLight" (API 3.0.0)
[Server] [12:36:24] [Server thread/INFO]: PocketMine-MP-DerivedVersion is distributed under the GPL License
[Server] [12:36:26] [Server thread/INFO]: Loading recipes...
[Server] [12:36:26] [Server thread/INFO]: Loading source plugin SAC v3.3.9
[Server] 
[Server] Fatal error: Declaration of DarkWav\SAC\SAC::onCommand(pocketmine\command\CommandSender $sender, pocketmine\command\Command $command, string $label, array $args): bool must be compatible with pocketmine\command\CommandExecutor::onCommand(pocketmine\command\CommandSender $sender, pocketmine\command\Command $command, $label, array $args) in /storage/emulated/0/PocketMine/plugins/SAC-master/src/DarkWav/SAC/SAC.php on line 18
[Server] [12:36:27] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[Server] [12:36:27] [Server thread/EMERGENCY]: Please upload the "/storage/emulated/0/PocketMine/crashdumps/Mon_Apr_9-12.36.27-UTC_2018.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
[PocketMine] Server was stopped.

**Comment by DarkWav** [comment]
Thanks for bug reporting!
You Seem to be using a non-official version / fork of PocketMine-MP. If i try to install version 3.3.9 with the latest PMMP release found [Here](https://github.com/pmmp/PocketMine-MP/releases) it starts up corrctly.
Sorry for the innovenience, but it is really hard to provide backwards and cross-fork compatiblity.
This plugin might but is not guaranteed to work with forks. I will always priorize compatiblity with
PocketMine-MP itself. Since an API update of PocketMine-MP most PMMP forks didn't update their PocketMine-API = If you code your Plugin for PMMP, it wont work on most forks.
Therefor, i can sadly only tell you that this plugin does not work with your server software because your server software appears to not run the latest version of the PocketMine-API, which is required to run SAC.
