### ISSUE TITLE
Sac sending hacker warnings to everyone

### ISSUE THREAD

**Issue by YHC2538** [DarkWav/SAC#77]
In plugin.yml I've set sac.admin default: false

So, it should only send hacker warning messages to staffs that have sac.admin or OPs.

But new players (Non-OP) are still able to see the hacker warning even when they don't have sac.admin permission.

**Comment by DarkWav** [comment]
Thanks for Bug reporting!
I will try to reproduce this issue ASAP.
Some info: default: False means noone will get the Permission by default, not even Ops.
Until a solution is found, you can set Verbose to false in config.

**Comment by DarkWav** [comment]
It appears to happen to quite a few people: #15 , #54 .
Im very sorry, i could not reproduce this issue. When I tested it myself, everything worked correctly.
Are you using any permissions management plugins? These might eventually unintendedly give sac.admin to all players with out you knowing about it.
If you use a Fork like Altray, there might be issues aswell.

**Comment by YHC2538** [comment]
No forks, I'm using pmmp latest. And I am using pureperms too. But I don't think that's the one causing the error.

**Comment by DarkWav** [comment]
1. would't recommend changing plugin.yml at all.
2. Are you giving the "sac.admin" permission to some non-op players via pureperms?
If you do, you might have exidentally given the permission to all players insted if only the ones you wanted to.

**Comment by YHC2538** [comment]
1. I have reinstalled the plugin, same problem.

2. And I have checked the permissions, I only gave it Mods and Trainees, but Guests can still see the messages smh.

**Comment by DarkWav** [comment]
Ok, thanks. 
Im very sorry :( ...
Since i cannot reproduce or spot the problem i won't be able to fix it.
For now, you'll have to entirely disable verbose Output of SAC (set Verbose to false in config) or allow all
players to see hacker warnings.
Maybe someone else (preferrably with knowledge about pureperms) can help you, everything about PMMP is open source, so someone might be able to help you.
You could maybe ask on PMMP forums.
Anyways, thanks a lot for bug reporting. I hope i could help a bit.

**Comment by YHC2538** [comment]
Its fine. Thank you a lot for helping me! :)
