### ISSUE TITLE
auth antiforceop issue

### ISSUE THREAD

**Issue by mihnea91** [DarkWav/SAC#8]
well ,there is an issue in your plugin , if you activate antiforceop feature and you also have an auth plugin the members group with that permission legitop will be kicked before they can write their passwords to login .

**Comment by DarkWav** [comment]
yes, i im short befor releasing VAC 3.0.2 and i can rewrite any auth plugin you want (for Example simpleauth) so that wont happen... but this will only appear on some auth plugins.
I could make a kind of compatVAC plugin that pervents that. i am sure not every auth plugin causes that. you could try some other auth plugins.

The thing is that the players don´t revice the permission legitop OR you did something wrong.

I can try to provide compatiblity with simpleauth.  (if you want that).
BUT i cant support any auth-plugin that isnt public. (or a fork of a public one).

**Comment by Infernus102** [comment]
did u fix fly detection and speed detection?

**Comment by DarkWav** [comment]
Yes i fixed speed and if fly stilll couses roblems then i can say that it is not happening to me (I test with genisys.)
